dataset:
  dataset_name: "librispeech"

  audio:
    or_sample_rate: 16000
    sample_rate: 16000
    max_wav_value: 32768.0
    win_len: 256
    max_len: 48000

  path:
    raw_path: "./dataset/LibriSpeech"

  mel:
    n_fft: 1024
    hop_length: 256
    win_length: 1024