model:
  msg_dimension:
    demucs: 768

  demucs:
    chin: 1
    chout: 1
    hidden: 48
    depth: 5
    kernel_size: 8
    stride: 4
    causal: True
    resample: 4
    growth: 2
    max_hidden: 10_000
    normalize: True
    glu: True
    rescale: 0.1
    floor: 1e-3
    sample_rate: 5_000

  seanet_detector:
    channels: 1
    output_dim: 32
    dimension: 128
    n_filters: 32
    n_residual_layers: 3
    ratios: [8, 5, 4, 2]
    activation: "ELU"
    activation_params: {"alpha": 1.0}
    norm: "weight_norm"
    norm_params: {}
    kernel_size: 7
    last_kernel_size: 7
    residual_kernel_size: 3
    dilation_base: 2
    causal: False
    pad_mode: "reflect"
    true_skip: True
    compress: 2
    lstm: 1
    disable_norm_outer_blocks: 0

  seanet_embedder:
    encoder:
      channels: 1
      dimension: 128
      n_filters: 32
      n_residual_layers: 3
      ratios: [8, 5, 4, 2]
      activation: "ELU"
      activation_params: {"alpha": 1.0}
      norm: "weight_norm"
      norm_params: {}
      kernel_size: 7
      last_kernel_size: 7
      residual_kernel_size: 3
      dilation_base: 2
      causal: False
      pad_mode: "reflect"
      true_skip: True
      compress: 2
      lstm: 1
      disable_norm_outer_blocks: 0

    decoder:
      channels: 1
      dimension: 128
      n_filters: 32
      n_residual_layers: 1
      ratios: [8, 5, 4, 2]
      activation: "ELU"
      activation_params: {"alpha": 1.0}
      norm: "weight_norm"
      norm_params: {}
      kernel_size: 7
      last_kernel_size: 7
      residual_kernel_size: 3
      dilation_base: 2
      causal: False
      pad_mode: "reflect"
      true_skip: True
      compress: 2
      lstm: 0
      disable_norm_outer_blocks: 0
      trim_right_ratio: 1.0

  WM1d:
    nlayers_decoder: 6
    hidden_size: 128

  WM2d:
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    block: 'skip' #'skip', 'relu'
    layers_CE: 3
    layers_EM: 6
    latent_dim: 128


  structure:
    transformer: 0
    conv2: 0
    conv2mel: 1
    mel: 1
    share: 0
    vocoder_step: 0
    ab: 0

  robust: 1

  dim:
    embedding: 512

  layer:
    nlayers_encoder: 6
    attention_heads_encoder: 8
    nlayers_decoder: 6
    attention_heads_decoder: 8

  wm:
    kernel_size: 3
    n_temporal_layer: 2

  audio:
    kernel_size: 3
    n_temporal_layer: 2


  conv_module:
    hidden_size: 32
    kernel_size: 13
    n_temporal_layer: 5
    n_linear_layer: 0
    hidden_dim: 512


  conv2:
    block: 'skip' #'skip', 'relu'
    layers_CE: 3
    layers_EM: 6
    hidden_dim: 64
    LSTM_dim: 128


  test:
    model_path: "results/ckpt/half_vunlerable_watermark/pth" 
    model_name: False
    index: -1
